### PR TITLE
Generate enums in Github Actions

### PR DESCRIPTION
**Pull request by tschaume**
@esoteric-ephemera @tsmathis Regenerating the enums removes the `_missing_` classmethod for the VASP calc types. Is that being used/needed anywhere?

### CODE REVIEW

**Comment by tsmathis** [comment]
I'm not seeing the use of `__missing__` anywhere in emmet

**Comment by tsmathis** [comment]
I'll also close #1094 in favor of this

**Comment by tsmathis** [comment]
> I'm not seeing the use of `__missing__` anywhere in emmet

sorry, that's `_missing_` actually isn't it. But same thing, non-existent as far as I can tell

**Comment by esoteric-ephemera** [comment]
@tschaume, `_missing_` is needed for case insensitivity, see [this issue](https://github.com/materialsproject/api/issues/869) that @munrojm fixed a while ago. Without `_missing_`, pydantic throws validation errors (checked for that specific MPID in the issue, `mp-2048877`), adding it back resolves them

I'd like to take a crack at having the action generate a yaml file, and instantiating the enums from yaml. I'll make a separate PR for that

**Pull request merged**
