### PR TITLE
Migrationgraphdoc

### PR DESCRIPTION
**Pull request by hmlli**
*Start with a description of this PR. Then edit the list below to the items that make sense for your PR scope, and check off the boxes as you go!*

## Contributor Checklist

- [X] I have broken down my PR scope into the following TODO tasks
   -  [X] add file for migrationgraphdoc
   -  [x] all functionalities added to migrationgraphdoc
- [x] I have run the tests locally and they passed.
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### CODE REVIEW

**Comment by hmlli** [comment]
@munrojm Hi Jason! Do I need to add a test to this? If so, is there a good example test file that I can go off of? If not, I believe it's ready for review! Thanks!

**Comment by munrojm** [comment]
Hey @hmlli! Thanks for the PR! Left one comment.

As for tests, you should add one to test the class method attached to the doc model. Here are the tests for the electrode-related document models for example: https://github.com/materialsproject/emmet/blob/main/tests/emmet-core/test_electrodes.py.

**Comment by hmlli** [comment]
hi @munrojm, I've finished adding the test, this PR should be ready for review. Thanks :)

**Comment by munrojm** [comment]
@hmlli sounds good! Last thing is just addressing the comment I left above regarding the try-except block. After that is changed, I will merge.

**Pull request merged**
