### PR TITLE
Merge atomate2 taskdoc

### PR DESCRIPTION
**Pull request by utf**
I've merged in the atomate2 VASP task document into emmet.

There are currently no breaking changes with the documents that were already in emmet. I've tried to ensure there are no changes to the task documents themselves, e.g., what is actually stored in the database rather than the schema itself. However, I would really appreciate it if you could try running any relevant builders using this branch to make sure everything still runs ok.

Here is a summary of the new fields added in this PR

- Potcar
  - pot_type
- InputDoc
  - parameters
  - psuedo_potentials
  - potcar_spec
  - xc_override
  - is_lasph
  - is_hubbard
  - hubbards
- OutputDoc
  - energy_per_atom
  - bandgap
- TaskDoc
  - Now subclasses StructureMetadata
  - structure
  - included_objects
  - vasp_objects
  - entry
  - author
  - icsd_id
  - transformations
  - additional_json
  - dir_name
- TaskType now imported from emmet.core.vasp.enums (existed already)
- CalcsReversedDoc -> Calculation from emmet.core.vasp.calculation (added in this PR)
  - Existing fields remain the same, lots of new fields added.

### CODE REVIEW

**Comment by utf** [comment]
I fixed some mypy errors, but from what I can tell there are lots unrelated to this PR.

**Comment by munrojm** [comment]
Thanks @utf! This looks great. I am in the process of fixing the mypy errors on `main`. I'll get those into your branch and re-run the tests. 

Happy to do a test build with this branch before merging as well. How quickly are you looking to have these changes incorporated?

**Comment by utf** [comment]
Thanks Jason! Would a week timeframe be reasonable? I've implemented the necessary changes in an atomate2 branch so would need to do a timed release.

**Comment by munrojm** [comment]
A week should be OK. I can get it started either tomorrow or on Friday and have it run through the weekend.

**Comment by utf** [comment]
Thank you! To be honest, it could definitely be longer if a week would be too tight.

**Comment by munrojm** [comment]
No worries! Should be able to get it running by Friday. I will ping you as it finishes and I am able to take a look at the collections.

**Comment by munrojm** [comment]
@utf, I ran a build on all of the staging collections and everything looks good to me. I don't expect any other issues to be introduced in the full build by these changes. Are you okay if I merge this now?

**Comment by utf** [comment]
Thanks Jason! Happy for you to merge. 

Is it possible to also get a version release?

**Comment by munrojm** [comment]
Yup! Merging now.

**Pull request merged**
