### PR TITLE
Pydantic v2

### PR DESCRIPTION
**Pull request by janosh**
Just ran the `bump-pydantic` CLI [@mkhorton mentioned](https://github.com/materialsproject/emmet/issues/768#issuecomment-1644523321). Let's see what CI says.

### CODE REVIEW

**Comment by janosh** [comment]
@munrojm Could we change the `emmet` CI settings to not cancel all runs as soon as one throws an error? Would be nice in this case to see if any tests failed but they're not run because a `mypy` error aborted all other GH actions.

**Comment by munrojm** [comment]
@janosh sure feel free to change the workflow. I also just updated the requirements files, so if you rebase on main you won't have the test issues from the previous pmg version.

**Comment by janosh** [comment]
Looks like there's still some manual work to be done:

```py
ImportError: cannot import name 'field_validator' from 'pydantic'
```

**Comment by munrojm** [comment]
Note this needs changes in monty which are being worked on here: https://github.com/munrojm/monty/tree/pydantic_v2

**Comment by mkhorton** [comment]
Will this leave monty supporting both versions of pydantic, or is it either/or?

**Comment by munrojm** [comment]
My current plan is to just have it support >2.0.

**Comment by utf** [comment]
I'm also interested in this. Keen to hear any issues you run into along the way.

**Comment by munrojm** [comment]
I still have to figure out how to translate the monty stuff. It requires going under the hood quite a bit in pydantic. It was taking me a while, and I got pulled away for other issues. Still trying to get back to it...

**Comment by mkhorton** [comment]
What’s the specific issue? Kinda curious myself, I’ve been working with pydantic more recently.

**Comment by arosen93** [comment]
The monty PR was now merged and a new version was released, so I think progress can now be made here 😄

**Comment by janosh** [comment]
I'll get on it, probably next week.

**Comment by arosen93** [comment]
Might want to check with @munrojm. Sounded like he has a custom branch of most of the MP stack with updated support for Pydantic 2.

**Comment by munrojm** [comment]
The `pydantic-2` branch has my changes. I am almost done with everything.

**Comment by sphuber** [comment]
Appreciate the work by the materialsproject. Do you guys have a time estimate for this fix and a release? We would like to move to pydantic v2 but this is the last blocking dependency.

**Comment by munrojm** [comment]
@sphuber yes, everything is almost in place. Should be released early next week.

**Pull request merged**
