### PR TITLE
Several `TaskDoc` improvements

### PR DESCRIPTION
**Pull request by mkhorton**
I noticed this was currently missing, so an important add for parity with the `task_valid.TaskDocument`.

If I have a minute, I may append to this PR to formalize the `Entry` model to ensure these fields are explicitly defined (since they're required for the compatibility scheme), otherwise the PR could be merged as-is.

### CODE REVIEW

**Comment by mkhorton** [comment]
I have also added a `TaskDoc.from_vasprun` method. This will log a warning, since some information from the OUTCAR will be missing, but the `TaskDoc` will still be valid and complete.

**Comment by mkhorton** [comment]
Hi @munrojm, could you confirm the correct key for corrected entries? This warning seems inconsistent: https://github.com/materialsproject/emmet/blob/4ba058a2631b9fb11a8022434eb52d646de061e6/emmet-builders/emmet/builders/materials/corrected_entries.py#L52-L57

In the ThermoBuilder, it seems to suggest it's `chemsys`?

https://github.com/materialsproject/emmet/blob/4ba058a2631b9fb11a8022434eb52d646de061e6/emmet-builders/emmet/builders/materials/thermo.py#L59-L64

I can correct in this PR, but wanted to confirm first.

**Comment by munrojm** [comment]
The correct key for corrected entries is indeed `chemsys`. That first block has a typo. The data for every `thermo_id` is contained in the `entries` dict, with `thermo_id` values as keys.

**Comment by mkhorton** [comment]
@munrojm I think this is ready for review/merge

**Comment by munrojm** [comment]
@mkhorton no concerns on my end! Looks good to me. Will merge now.

**Pull request merged**
