### PR TITLE
Conversion electrode builder minor changes

### PR DESCRIPTION
**Pull request by kim-jiyoon**
I uppdated the conversion electrode builder to include entry_ids for reactant and product compositions listed in the conversion reactions.

Given a conversion electrode reaction, a dictionary called "formula_id_mapping" is added to the conversion electrode document to map the compositions from the conversion reaction to entry_ids found in the respective phase diagrams:

doc["reaction"]: 
{ "@module" : "pymatgen.analysis.reaction_calculator", "@class" : "BalancedReaction", 
"reactants" : 
{ "Co4 O8" : 1.000000000000002, 
"O8" : 0.9999999999999998, 
"Li1" : 1.999999999999961 }, 
"products" : 
{ "Li8 Co16 O32" : 0.24999999999999623, 
"O8" : 1.000000000000018 } }

doc["formula_id_mapping"]:
{ "Co4 O8" : "mp-1400906-GGA+U", 
"Li1" : "mp-51-GGA", 
"O8" : "mp-723285-GGA", 
"Li8 Co16 O32" : "mp-774082-GGA+U" }

@jmmshn @munrojm @yang-ruoxi

### CODE REVIEW

**Comment by munrojm** [comment]
Thanks @kim-jiyoon. I will fix the linting issues on main, re-run your tests and merge when they pass.

**Comment by munrojm** [comment]
@kim-jiyoon are you good to have this merged?

**Comment by kim-jiyoon** [comment]
> @kim-jiyoon are you good to have this merged?

Hi Jason, thanks for checking in! I just wanted to double check something with Jimmy before merging (he said he will get back to me soon) and then I can ping you if that's alright?

**Comment by jmmshn** [comment]
@munrojm @kim-jiyoon Looks good ready to merge

**Pull request merged**
