### PR TITLE
 Elasticity doc and builder

### PR DESCRIPTION
**Pull request by mjwen**
Schema and builder for elastic tensors and derived properties. 

This PR regenerates the builders for elastic tensor calculations. It

- creates schema for elastic tensors, compliance tensors, derived properties, as well as fitting data; the hope is to enable full provenance tracking and regeneration of the docs. 

- ports three different elastic tensor fitting methods from atomate, which can be selected at the builder level

- filter tasks by INCAR params and task completion time in causes multiple tasks are associated with the same material 

TODO: more unit tests should be added

### CODE REVIEW

**Comment by mjwen** [comment]
@munrojm I plan to have the PR merged soon. Can you first approve running workflows? Also, it seems you have already added some elasticity doc; now I just overwrite it by this PR. We can probably discuss more offline. In addition, there are some TODOs that I need to check with you.

**Comment by munrojm** [comment]
Hi @mjwen, no problem. Happy to meet and make this a priority.

**Comment by mjwen** [comment]
@munrojm ready for review! 

There are 3 to 4 TODOs in `builders/materials/elasticity.py` and `builders/vasp/materials.py`, which we may want to discuss more.

**Comment by mjwen** [comment]
@munrojm good to go.

**Comment by munrojm** [comment]
All looks good to me. Once the tests are passing, I will merge.

**Comment by munrojm** [comment]
Thanks again for all your work on this @mjwen! I am going to go ahead and merge.

**Pull request merged**
