### PR TITLE
Fixes a few issues in wf builder and elastic builder

### PR DESCRIPTION
**Pull request by montoyjh**
Incremental building in the elastic builder wasn't working properly, and the query for the tasks database needed to be modified slightly for compatibility with more recent atomate versions.  Also, the property workflow builder needs a cursor timeout that's longer than standard because insertion of fireworks takes a bit of time.

### CODE REVIEW

**Comment by montoyjh** [comment]
pause on this to fix a warnings issue

**Comment by montoyjh** [comment]
This is ready, but looks like Travis tests are failing b/c of something upstream in the pymatgen release from today in the structure similarity builders. @nisse3000 would you mind taking a look when you get a chance?

**Comment by nisse3000** [comment]
@montoyjh, sure thing.

**Comment by nisse3000** [comment]
Hey @montoyjh, I've made a pull request (#37) that aims to switch to the most recent pymatgen version plus addressing the label problem in the tests of the site-descriptor builder. Several of the near-neighbor algorithms in pymatgen are quickly evolving and changing names, which seemed to have been the problem here.

**Comment by montoyjh** [comment]
This should be done, gonna merge if no objections.

**Pull request merged**
