### PR TITLE
[WIP] Updates to magnetism, bond, mp_website builders, new bond_valence, mp_website_digest builders

### PR DESCRIPTION
**Pull request by mkhorton**
Marked as a [WIP] but these have been tested in Jupyter, and have partial/complete builds available.

I modified a few before making the PR to match house style/support incremental builds, so I may have introduced a bug hence the WIP, but I wanted to share before I take off for a few days ...

Have:

* new bond valence builder
* more magnetism metadata
* digest builder (it's very basic, we probably want to discuss want to include though)
* updates to bond builder

I have about a 2/3rds bond valence build, a full magnetism build, a sample digest build, and a huge bond build I could copy-build over if necessary. Most of these are quite fast apart from the bond build however.

### CODE REVIEW

**Comment by shyamd** [comment]
Should i get rid of the WIP improvements to the mag builder PR?

**Comment by mkhorton** [comment]
Yes, thanks — I just closed the other one, it’s all wrapped into this one.

**Comment by mkhorton** [comment]
Think this is ready to merge once tests pass.

Some additional magnetism updates and bond statistics updates to come as a separate PR.

Have made a few minor edits to mp_website doc, no breaking changes.

**Comment by mkhorton** [comment]
Merging, note bumped requirements.

@shyamd if there are any issues with changes to mp_website builder ping me + I'll fix asap, but all should be fine (tests pass....though I'm not sure we have mp_website tests specifically?), changes here: https://github.com/materialsproject/emmet/pull/64/files#diff-95824fcda1e1730ae54d52377edf7aad

**Pull request merged**
