### PR TITLE
Task doc validation changes

### PR DESCRIPTION
**Pull request by munrojm**
This PR make some small changes to how some of the `TaskDoc` fields are validated to ensure it can be used with the `mp-api` client.

### CODE REVIEW

**Comment by munrojm** [comment]
@utf, do you have any issues with these small changes? I've tested this with the current client and a large amount of the task collection data.

**Comment by munrojm** [comment]
I'm realizing the changes are hard to see because of the formatting. Here is a summary:

- custodian `corrections` set to `List[Any]`
- `task_type` validated as both `CalcType` or `TaskType`
- `CalculationInput` now also uses pmg `Kpoints` object in validation
- `epsilon_*` matrices swapped to `Tensor3R` for `Tuple` -> `List` validation for `[]` cases

**Comment by utf** [comment]
Hi @munrojm, those changes all look fine to me!

**Comment by utf** [comment]
Hi @munrojm, this is causing issues with atomate2 task validation.

The issue is that the epsilon_* matrices are not rank 3 tensors, they are rank 2 tensors.

Is there a reason you changed them to rank 3?

**Comment by munrojm** [comment]
@utf, that is definitely a mistake and should be switched. The reason I switched the type was related to the Tuple vs List validation issue for cases when it is empty.

**Pull request merged**
