### PR TITLE
Magnetism builder updates

### PR DESCRIPTION
**Pull request by munrojm**
This PR updates the magnetism builder. It also fixes chunking for some additional legacy builders.

### CODE REVIEW

**Comment by munrojm** [comment]
OK. If we build with that `task_id` the only caveat would be that the magnetism collection would not have an entry for every material. This is because `origins` is not populated in deprecated material entries. This is different from the other property collections, but probably won't be an issue.

**Comment by mkhorton** [comment]
Can you clarify? Every material has a thermo doc entry -- why would ever entry not have a magnetism doc entry?

**Comment by munrojm** [comment]
Thermo is also an exception exception. Only docs for non deprecated materials are built. For the other properties, deprecated materials have an entry, but it is indicated as deprecated in the property doc.

**Comment by munrojm** [comment]
Thermo is also an exception. Only docs for non deprecated materials are built is what I meant. For the other properties, deprecated materials have an entry, but it is indicated as deprecated in the property doc.

**Comment by munrojm** [comment]
Thermo is also an exception. Only docs for non deprecated materials are built is what I meant. For the other properties, deprecated materials have an entry, but it is indicated as deprecated in the property doc.

**Comment by mkhorton** [comment]
Ah, understood. I think it's ok if this is only built for non-deprecated materials.

**Comment by munrojm** [comment]
Okay, that sounds good. I will make those changes then.

**Pull request merged**
