### PR TITLE
[WIP] `TaskDoc` changes

### PR DESCRIPTION
**Pull request by munrojm**
This PR merges the task document models into a single one that can be used by both the validation builder, and the API client.

### CODE REVIEW

**Comment by mkhorton** [comment]
What is meaning/possible values of `state`? Why the change in import/filename?

**Comment by mkhorton** [comment]
Ah, I see `Status` -- should this not be `State`? (also typo in `SUCESS`)

**Comment by munrojm** [comment]
I have renamed it.

I have had a goal to merge the two task doc models in emmet-core for a while now. I think I may just use this PR to do it... These changes were in response to a meeting with @acrutt.

**Comment by mkhorton** [comment]
Makes sense, I think I was just confused by the `_valid`. May this not cause confusion because a `TaskDocument` with state `VALID` may still generated a `ValidationDoc` with `.valid == False`?

**Comment by arosen93** [comment]
Looks like this can potentially be closed, @munrojm?

**Pull request closed without merging**
